services:
  tunnel:
    image: localtonet/localtonet:latest
    container_name: localtonet
    restart: unless-stopped
    environment:
      - AUTH_TOKEN=${LOCALTONET_TOKEN}
    healthcheck:
      test: [ "CMD-SHELL", "ps aux | grep [l]ocaltonet || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s