version: '3.8'

services:
#  app:
#    build: ./Backend
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8000"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#    environment:
#      - DEBUG=1
#      - ALLOWED_HOSTS=.ngrok-free.app,localhost,127.0.0.1
#
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - AUTHTOKEN=$NGROK_AUTHTOKEN
    command:
      - "http"
      - "app:8000"

    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4040/api/tunnels | grep -q 'public_url' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "4040:4040"