# Generated by Django 6.0.3 on 2026-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0002_customer_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(default='Rua Nelson Tigrão, 15, Vila Missionária, CEP: 04430-165', max_length=255),
        ),
    ]
