# Generated by Django 6.0.3 on 2026-04-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0003_appointment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='senha',
            field=models.CharField(default='temp', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=19),
        ),
    ]
