# Generated by Django 6.0.3 on 2026-05-02 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0003_appointment_location_customer_deleted_customer_senha_and_more'),
        ('Agendamento', '0004_customer_senha_alter_customer_name_and_more'),
    ]

    operations = [
    ]
